### ISSUE TITLE
亚马逊领的游戏无法同步

### ISSUE THREAD

**Issue by HUBBLEEEEEE** [sffxzzp/EpicInfo#2]
![image](https://github.com/sffxzzp/EpicInfo/assets/77613734/0919b4df-e650-44d9-9a6d-c75017399c60)
![image](https://github.com/sffxzzp/EpicInfo/assets/77613734/d0442b2b-0286-442a-bfbc-2774b9d88022)
![image](https://github.com/sffxzzp/EpicInfo/assets/77613734/190be5da-66cb-4fde-9558-461875182377)

**Comment by sffxzzp** [comment]
我这里测试正常，可能是脚本引入的文件没能正常自动更新。
检查一下对应脚本的外部页签，看下是否正常更新。

![image](https://github.com/sffxzzp/EpicInfo/assets/3407292/4e372ad2-d3d8-4c05-9041-b6de27606500)

**Comment by sffxzzp** [comment]
检查了一下，引用的加速代理 ghproxy.com 会造成 offerid.json 以及 namespace.json 产生滞后，现已调整回直接从 Github 上读取。
